const CONFIG = {
  MAP: {
    DEFAULT_CENTER: [42.82, -83.78],
    DEFAULT_ZOOM: 15,
    MIN_ZOOM: 10,
    MAX_ZOOM: 19,
    CACHE_MIN_ZOOM: 14,
    CACHE_MAX_ZOOM: 18,
    CLUSTER_RADIUS_METERS: 20,
    CLUSTER_MIN_COUNT: 3,
    CLUSTER_NEARBY_MULTIPLIER: 1.5,
  },
  TILE_PROVIDERS: {
    esriImagery: {
      name: 'Satellite (No Labels)',
      url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
      attribution: 'Tiles &copy; Esri &mdash; Source: Esri, Maxar, Earthstar Geographics',
      maxZoom: 19,
      subdomains: '',
    },
    cartoVoyager: {
      name: 'Roads (No Labels)',
      url: 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}.png',
      attribution: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors © <a href="https://carto.com/attributions">CARTO</a>',
      maxZoom: 19,
      subdomains: 'abcd',
    },
    osm: {
      name: 'OpenStreetMap (Labels)',
      url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      attribution: '© OpenStreetMap contributors',
      maxZoom: 19,
      subdomains: 'abc',
    },
    cartoLight: {
      name: 'Light (No Labels)',
      url: 'https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png',
      attribution: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors © <a href="https://carto.com/attributions">CARTO</a>',
      maxZoom: 19,
      subdomains: 'abcd',
    },
  },
  GBIF: {
    SUGGEST_URL: 'https://api.gbif.org/v1/species/suggest',
    MATCH_URL: 'https://api.gbif.org/v1/species/match',
    LOOKUP_URL: 'https://api.gbif.org/v1/species',
    MAX_SUGGEST_RESULTS: 8,
    CACHE_MAX_AGE_DAYS: 90,
  },
  EXPORT: {
    INAT_COMBINE_THRESHOLD_DEFAULT: 5,
    JITTER_LOW_METERS: 50,
    JITTER_MEDIUM_METERS: 150,
    JITTER_HIGH_METERS: 400,
    HTML_TILE_BUFFER_TILES: 2,
  },
  DB: {
    NAME: 'FieldSurveyDB',
    VERSION: 1,
    STORES: ['surveys', 'observations', 'stands', 'speciesCache', 'tileRegions', 'exportSettings'],
  },
  APP: {
    VERSION: '1.1.0',
    BUILD:   '2026-05-14 10:05',
    DEFAULT_SURVEYOR: '',
    DEFAULT_COUNTY: 'Livingston',
    DEFAULT_TOWNSHIP: 'Tyrone',
  },
};
